extract_words: true
raw_output_filename: raw_pages.json
sections_output_filename: sections.json
chunks_output_filename: chunks.json
sections_tree_filename: sections_tree.mmd
sections_related_filename: sections_related.mmd
keywords_file: config/keywords.txt
update_keywords: false
auto_classify_subsections: false
